### ISSUE TITLE
delete()'s behavior when key doesn't exist in the tree

### ISSUE THREAD

**Issue by Shynar88** [kaist-cp/helpdesk#122]
What should be delete()'s behavior when key doesn't exist in the tree? 
In comments it is written: "Returns `Err(())` if `key` was vacant." This covers case when key is in the tree, but value is None. What about the case when key doesn't exist in the tree? Should we also return Err?

**Comment by bprovot** [comment]
That depends on how you implemented your `find` function. Technically if you find the right node (Ordering::Equal) either the value is here or not here but the key is the right one. Otherwise (for Greater or Less) in all cases your key isn't there because you point at a node child (which would be the theoretical place for your node), so you just return Err.

**Comment by jeehoonkang** [comment]
I agree with @bprovot .

**Comment by jeehoonkang** [comment]
Closing, but feel free to reopen it if you have follow-up questions!
