### ISSUE TITLE
Question about the slide (p 81, lock coupling)

### ISSUE THREAD

**Issue by choi7023546** [kaist-cp/helpdesk#131]
"Read operations invalidates cache!"
What does this sentence mean? 
Does it mean that if read operation occurs while progressing write operation, "read operation" could invalidates cache of write operation's value..?

**Comment by zoonoo** [comment]
From what I've understood: 
It's the main difference between pessimistic and optimistic lock:
You're looking at a pessimistic lock. So when you run a read operation, you still have to acquire a lock for each node on the way. When you acquire a lock, you have to write the status of the lock to the memory. That's why this read operation invalidates cache.
Note how this problem is resolved by optimistic concurrency control in sequence lock.

**Comment by jeehoonkang** [comment]
I agree with @zoonoo .

**Comment by jeehoonkang** [comment]
Closing, but feel free to reopen it for follow-up questions.
