### ISSUE TITLE
Question on Re-certification

### ISSUE THREAD

**Issue by hushon** [kaist-cp/helpdesk#20]
Hello, could you please comment on why the behavior in below slide is concluded to be disallowed? 
In other words, what argument does promising semantics make, in order to reject re-certification of writing the promise, X=1?
![image](https://user-images.githubusercontent.com/16029022/66906196-35a4a080-f042-11e9-841b-7c2d3f217d76.png)

**Comment by jeehoonkang** [comment]
Suppose the right thread promised to write X=1 and read the promised message X=1 for r3.  But it's impossible because it's not certified: in certification, right after reading X=1 for r3:
- The right thread's per-thread view points to the promised message X=1;
- It may take the then branch; but
- It cannot fulfill the promised message X=1 because it's per-thread view is already pointing to it.  Recall that you have to write/fulfill a message **STRICTLY AFTER** your current per-thread view.

**Comment by goodCycle** [comment]
@jeehoonkang In the slide pg38, it said that
`Reading/writing happens after the current thread's view`
But when I perform promising semantics, it feels like only `writing` a message is impossible to do in the current per-thread view.
So, it means that we can `read` the message in the current per-thread view, am I understand right?

**Comment by goodCycle** [comment]
@jeehoonkang  pg38의 슬라이드에 적힌대로라면 thread view에서 콩나물 줄기가 x는 1이라는 메시지를 지나고 있다면 해당 쓰레드가 x=1을 읽을 수 **없다**고 생각했습니다. 
근데, promising semantics에서 thread별로 실행시킬 때, thread view가 해당 메시지를 지나고 있으면 그 값은 읽어도 되니까 `Reading/writing happens after the current thread's view` 라는 구절과 상충된다고 생각했습니다. 

writing을 하는 경우에 쓰레드 뷰가 x=1이라는 값을 이미 지나고 있다면, x=1을 또 다시 쓸 수 없다는 뜻이죠?
즉 x=2부터 writing이 가능하다는 의미로 이해해도 될까요?

**Comment by jeehoonkang** [comment]
Thank you for sharing a valuable question and answer---all by yourself!

**Comment by drzix** [comment]
If I change the question above to `r1=r2=1 and r3=0`, is it OK to re-certify `X=1` at then branch (regardless of coherence) and regard it as **ALLOWED**?

Because I think then the code will be get absolutely same semantics as `r3=X; r2=Y; ...` one.

**Comment by jeehoonkang** [comment]
@drzix 
- If r1=r2=1 and r3=0, it should be allowed because r2=Y and r3=X can be reordered in T2, as you said.
- Promising semantics allows it despite the fact that it observes coherence.  Indeed, reading 0 and then writing 1 is a coherent behavior.
