### ISSUE TITLE
borrowing child in cursor

### ISSUE THREAD

**Issue by ChristPi** [kaist-cp/helpdesk#39]
I have an error of reasoning and I cannot get around what I am wrong about.
When trying to traverse the Tree I borrow the child to look up the key and cannot borrow the child again if I want to do the same thing for the next node. I also tried doing a helper function to do it recursively but the multiple returns end up producing multiple borrows as well.
Even disregarding that, trying to create an instance of Cursor with Information I get always leads to me needing to borrow the child.
I have a faulty approach but have run out of ideas and think that I have an error of approach.
Can you give me a hint for what I am doing fundamentally wrong?
(for what I understand: the cursor function is a function finding the edge at where the key should be/is)

**Comment by tomtomjhj** [comment]
This is because of rustc's inability to correctly handle lifetimes + conditional return. See http://smallcultfollowing.com/babysteps/blog/2018/06/15/mir-based-borrow-check-nll-status-update/#polonius for the minimal example.
The only solution I know of is to cast the reference into raw ptr in order to forget the lifetime information and then deref the raw ptr (this is an unsafe operation) to get the value and make reference of it.
So the workaround for the problem shown in the link is like this:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=eff19d04f2e37c3d16bedcbba7efffc5

Please let me know if you find a better solution.
