### ISSUE TITLE
Structure of ART

### ISSUE THREAD

**Issue by anemoneflower** [kaist-cp/helpdesk#43]
Hi, I'm really confusing about the structure of the given ART skeleton code.

if I insert value 42 with key "aa", the cursor will have
- parent: root
- child: nodebox with child(leaf node with value 42)
- index: 0
- depth: 3
- length: 3

<Question 1>
Case 1: At this point, if I insert value 33 with key "ab", what cursor should be? I thought that it should be

- depth: 3
- child: nodebox with child(leaf node with value 33)

but I'm confusing with what should be parent, index, length.

<Question 2>
Case 2: What if I insert value 44 with key "bb"? My guess is

- parent: root
- child: nodebox with child(leaf node with value 44)
- index: 1
- depth: 3
- length: 3

Is this right?

Thanks:)

**Comment by dnkim** [comment]
I assumed that every cursor is the cursor used for looking up the value after insertion.
1. If "ab" is inserted into the tree, the key of the leaf node with 42 will be shrunk into "a$" and a new inner node with key "a" will be inserted above, then a new leaf node with key "b$" will be inserted as the second child of the newly inserted inner node with key "a". Therefore, the cursor will be:
depth: 3
parent: newly inserted inner node with key "a"
child: newly inserted leaf node with key "b$"
index: 1 (since it is the second child)
length: 2 (length between parent and cursor which is the length of "b$"
2. index should be 98 which is the ascii code for "b" since node128 uses the key for its index. (Actually, not sure that it is ascii code.). Also index for the very first cursor should be 97. However, we don't need to care about it because it is handled by node.rs.

**Comment by jeehoonkang** [comment]
@anemoneflower may I ask if you if the above comment answers your question?

**Comment by anemoneflower** [comment]
@jeehoonkang  Oh yes!!
Thanks a lot @dnkim !!
