### ISSUE TITLE
mutable handling

### ISSUE THREAD

**Issue by anemoneflower** [kaist-cp/helpdesk#60]
Hi, I'm trying to fixing mutable errors at my code.
I used "deref_mut" for a nodebox. And this deref_mut part is in the **{}** to make it separate scope. When I tried to use same nodebox **outside the scope** with mutable borrowing, it doesn't work. Is using **{}** not a solution to this problem?
If anyone knows a solution, please help me.
thanks :)

**Comment by tomtomjhj** [comment]
Most of the answers to questions about borrowing in the internet that uses `{ ... }` are invalid in the current version of rust because lifetimes are decided by the actual use, not by the lexical block (non-lexical lifetime). This means that rust's borrow checker is much more flexible now and you don't need to insert `{ ... }` in most cases. 
However, some issues are still not resolved. One of the example is described in https://github.com/kaist-cp/helpdesk/issues/39. If you are getting errors inside a loop, that might be the solution.

**Comment by anemoneflower** [comment]
Thanks!! I'll try it!
