### ISSUE TITLE
Concerns in using Entry API for deletion

### ISSUE THREAD

**Issue by qvntm** [kaist-cp/helpdesk#66]
I am not sure how we can further implement inner node shrinking/deleting when necessary. From my understanding, with the Entry API, we can only modify the shrink/delete the `cursor.child` and we can't delete/shrink the `cursor.parent` because we don't have mutable reference to its parent.

For example, when we insert value with 100 character key and delete it, we can only delete the leaf node and to delete the inner nodes, we basically have to re-traverse the tree top-down but the actual `key` info is lost so its impossible. So the only option left is to _periodically_ clean up the tree but the choice of _period_ is always a problem.

In my opinion, it seems more reasonable to not use Entry API for node deletion so we can delete/shrink the parents when appropriate. Am I missing something here?

**Comment by jeehoonkang** [comment]
I agree with you in that the current definition of cursor cannot cleanup the tree completely after resizing.  We have two choices:
- We can remember all ancestors in a cursor instead of an immediate one (i.e. parent) so that we can completely cleanup the tree after resizing.
- We give up to completely cleanup the tree and instead periodically cleanup the tree.

Both options look fine to my eyes.  Specifically, periodic (cleanup) functions sound not too bad to me because it's anyway needed for garbage collection or other kinds of "cleanup".
